# Default configuration for loongarch32-softmmu

CONFIG_SERIAL=y
CONFIG_SERIAL_ISA=y
CONFIG_I8257=y
CONFIG_PFLASH_CFI01=y
CONFIG_I8259=y
CONFIG_MALTA=y
CONFIG_SMBUS_EEPROM=y
CONFIG_AHCI=y
CONFIG_FRAMEBUFFER=y
CONFIG_LOONGARCH32=y
